"""on delete

Revision ID: 55db22d51bd7
Revises: 8022ca232d14
Create Date: 2025-04-16 11:03:28.484013

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "55db22d51bd7"
down_revision: Union[str, None] = "8022ca232d14"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "fk_property_values_property_uid_properties",
        "property_values",
        type_="foreignkey",
    )
    op.create_foreign_key(
        op.f("fk_property_values_property_uid_properties"),
        "property_values",
        "properties",
        ["property_uid"],
        ["uid"],
        ondelete="CASCADE",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("fk_property_values_property_uid_properties"),
        "property_values",
        type_="foreignkey",
    )
    op.create_foreign_key(
        "fk_property_values_property_uid_properties",
        "property_values",
        "properties",
        ["property_uid"],
        ["uid"],
    )
    # ### end Alembic commands ###
